name: Build osx

on:
  push:
    tags:
      - 'v*'     # build on tags (release)
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Show system info
        run: |
          sw_vers
          xcodebuild -version
          uname -a

      - name: Make build script executable
        run: chmod +x ./build_osx.sh

      - name: Run build script
        env:
          CI: true
        run: |
          set -euo pipefail
          sudo softwareupdate --install-rosetta --agree-to-license
          arch -x86_64 ./build_osx.sh

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: tunsafe-macos-build
          path: tunsafe_osx.zip

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: tunsafe_osx.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}